// Word data is vendored from badwords-list v2.0.1-4 (MIT) and LDNOOBW es/pt (CC BY 4.0).
// Sources: https://github.com/web-mech/badwords-list and https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words
// See THIRD_PARTY_NOTICES.md.
(() => {
  const BAD_WORDS = [
  "4r5e",
  "5h1t",
  "5hit",
  "a_s_s",
  "a55",
  "aborto",
  "amador",
  "anal",
  "anus",
  "ar5e",
  "aranha",
  "ariano",
  "arrse",
  "arse",
  "asesinato",
  "asno",
  "ass",
  "ass-fucker",
  "asses",
  "assfucker",
  "assfukka",
  "asshole",
  "assholes",
  "asswhole",
  "b!tch",
  "b00bs",
  "b17ch",
  "b1tch",
  "balalao",
  "ballbag",
  "balls",
  "ballsack",
  "bastard",
  "bastardo",
  "beastial",
  "beastiality",
  "bellend",
  "bestial",
  "bestiality",
  "bi+ch",
  "biatch",
  "bicha",
  "biscate",
  "bissexual",
  "bitch",
  "bitcher",
  "bitchers",
  "bitches",
  "bitchin",
  "bitching",
  "bloody",
  "blow job",
  "blowjob",
  "blowjobs",
  "boceta",
  "boiolas",
  "bollera",
  "bollock",
  "bollok",
  "boner",
  "boob",
  "boobs",
  "booobs",
  "boooobs",
  "booooobs",
  "booooooobs",
  "bosta",
  "braulio de borracha",
  "breasts",
  "buceta",
  "bugger",
  "bum",
  "bumbum",
  "bunny fucker",
  "burro",
  "butt",
  "butthole",
  "buttmuch",
  "buttplug",
  "c0ck",
  "c0cksucker",
  "cabrao",
  "cabron",
  "caca",
  "cacete",
  "cagar",
  "camisinha",
  "caralho",
  "carpet muncher",
  "cawk",
  "cerveja",
  "chink",
  "chochota",
  "chupada",
  "chupapollas",
  "chupar",
  "chupeton",
  "cipa",
  "cl1t",
  "clit",
  "clitoris",
  "clits",
  "cnut",
  "cocaina",
  "cock",
  "cock-sucker",
  "cockface",
  "cockhead",
  "cockmunch",
  "cockmuncher",
  "cocks",
  "cocksuck",
  "cocksucked",
  "cocksucker",
  "cocksucking",
  "cocksucks",
  "cocksuka",
  "cocksukka",
  "coito",
  "cok",
  "cokmuncher",
  "coksucka",
  "colhoes",
  "comer",
  "cona",
  "concha",
  "concha de tu madre",
  "cono",
  "consolo",
  "coon",
  "coprofagia",
  "corno",
  "cox",
  "crap",
  "cu",
  "culo",
  "cum",
  "cummer",
  "cumming",
  "cums",
  "cumshot",
  "cunilingus",
  "cunillingus",
  "cunnilingus",
  "cunt",
  "cuntlick",
  "cuntlicker",
  "cuntlicking",
  "cunts",
  "cyalis",
  "cyberfuc",
  "cyberfuck",
  "cyberfucked",
  "cyberfucker",
  "cyberfuckers",
  "cyberfucking",
  "d1ck",
  "damn",
  "dar o rabo",
  "dick",
  "dickhead",
  "dildo",
  "dildos",
  "dink",
  "dinks",
  "dirsa",
  "dlck",
  "dog-fucker",
  "doggin",
  "dogging",
  "donkeyribber",
  "doosh",
  "drogas",
  "duche",
  "dum raio",
  "dyke",
  "ejaculate",
  "ejaculated",
  "ejaculates",
  "ejaculating",
  "ejaculatings",
  "ejaculation",
  "ejakulate",
  "esperma",
  "esporra",
  "f u c k",
  "f u c k e r",
  "f_u_c_k",
  "f4nny",
  "fag",
  "fagging",
  "faggitt",
  "faggot",
  "faggs",
  "fagot",
  "fagots",
  "fags",
  "fanny",
  "fannyflaps",
  "fannyfucker",
  "fanyy",
  "fatass",
  "fcuk",
  "fcuker",
  "fcuking",
  "fecal",
  "feck",
  "fecker",
  "felching",
  "fellate",
  "fellatio",
  "fiesta de salchichas",
  "filho da puta",
  "fingerfuck",
  "fingerfucked",
  "fingerfucker",
  "fingerfuckers",
  "fingerfucking",
  "fingerfucks",
  "fistfuck",
  "fistfucked",
  "fistfucker",
  "fistfuckers",
  "fistfucking",
  "fistfuckings",
  "fistfucks",
  "flange",
  "foda",
  "foda-se",
  "foder",
  "follador",
  "follar",
  "fook",
  "fooker",
  "frango assado",
  "fuck",
  "fucka",
  "fucked",
  "fucker",
  "fuckers",
  "fuckhead",
  "fuckheads",
  "fuckin",
  "fucking",
  "fuckings",
  "fuckingshitmotherfucker",
  "fuckme",
  "fucks",
  "fuckwhit",
  "fuckwit",
  "fudge packer",
  "fudgepacker",
  "fuk",
  "fuker",
  "fukker",
  "fukkin",
  "fuks",
  "fukwhit",
  "fukwit",
  "fux",
  "fux0r",
  "gangbang",
  "gangbanged",
  "gangbangs",
  "gaylord",
  "gaysex",
  "gilipichis",
  "gilipollas",
  "goatse",
  "god",
  "god-dam",
  "god-damned",
  "goddamn",
  "goddamned",
  "gozar",
  "grelho",
  "hacer una paja",
  "haciendo el amor",
  "hardcoresex",
  "hell",
  "heroina",
  "heshe",
  "heterosexual",
  "hija de puta",
  "hijaputa",
  "hijo de puta",
  "hijoputa",
  "hoar",
  "hoare",
  "hoer",
  "homem gay",
  "homo",
  "homoerotico",
  "homosexual",
  "hore",
  "horniest",
  "horny",
  "hotsex",
  "idiota",
  "imbecil",
  "inferno",
  "infierno",
  "jack-off",
  "jackoff",
  "jap",
  "jerk-off",
  "jilipollas",
  "jism",
  "jiz",
  "jizm",
  "jizz",
  "kapullo",
  "kawk",
  "knob",
  "knobead",
  "knobed",
  "knobend",
  "knobhead",
  "knobjocky",
  "knobjokey",
  "kock",
  "kondum",
  "kondums",
  "kum",
  "kummer",
  "kumming",
  "kums",
  "kunilingus",
  "l3i+ch",
  "l3itch",
  "labia",
  "lameculos",
  "lesbica",
  "lolita",
  "lust",
  "lusting",
  "m0f0",
  "m0fo",
  "m45terbate",
  "ma5terb8",
  "ma5terbate",
  "maciza",
  "macizorra",
  "maldito",
  "mama",
  "mamada",
  "marica",
  "maricon",
  "mariconazo",
  "martillo",
  "masochist",
  "master-bate",
  "masterb8",
  "masterbat*",
  "masterbat3",
  "masterbate",
  "masterbation",
  "masterbations",
  "masturbate",
  "merda",
  "mierda",
  "mo-fo",
  "mof0",
  "mofo",
  "mothafuck",
  "mothafucka",
  "mothafuckas",
  "mothafuckaz",
  "mothafucked",
  "mothafucker",
  "mothafuckers",
  "mothafuckin",
  "mothafucking",
  "mothafuckings",
  "mothafucks",
  "mother fucker",
  "motherfuck",
  "motherfucked",
  "motherfucker",
  "motherfuckers",
  "motherfuckin",
  "motherfucking",
  "motherfuckings",
  "motherfuckka",
  "motherfucks",
  "muff",
  "mutha",
  "muthafecker",
  "muthafuckker",
  "muther",
  "mutherfucker",
  "n1gga",
  "n1gger",
  "nazi",
  "nigg3r",
  "nigg4h",
  "nigga",
  "niggah",
  "niggas",
  "niggaz",
  "nigger",
  "niggers",
  "nob",
  "nob jokey",
  "nobhead",
  "nobjocky",
  "nobjokey",
  "numbnuts",
  "nutsack",
  "orgasim",
  "orgasims",
  "orgasm",
  "orgasms",
  "orina",
  "p0rn",
  "paneleiro",
  "passar um cheque",
  "pau",
  "pawn",
  "pecker",
  "pedo",
  "peidar",
  "pendejo",
  "penis",
  "penisfucker",
  "pervertido",
  "pezon",
  "phonesex",
  "phuck",
  "phuk",
  "phuked",
  "phuking",
  "phukked",
  "phukking",
  "phuks",
  "phuq",
  "pigfucker",
  "pimpis",
  "pinche",
  "pinto",
  "pis",
  "piss",
  "pissed",
  "pisser",
  "pissers",
  "pisses",
  "pissflaps",
  "pissin",
  "pissing",
  "pissoff",
  "poop",
  "porn",
  "porno",
  "pornography",
  "pornos",
  "porra",
  "prick",
  "pricks",
  "pron",
  "prostituta",
  "pube",
  "pusse",
  "pussi",
  "pussies",
  "pussy",
  "pussys",
  "puta",
  "puta que pariu",
  "puta que te pariu",
  "queca",
  "racista",
  "ramera",
  "rectum",
  "retard",
  "rimjaw",
  "rimming",
  "s hit",
  "s_h_i_t",
  "s.o.b.",
  "sacanagem",
  "saco",
  "sadico",
  "sadist",
  "schlong",
  "screwing",
  "scroat",
  "scrote",
  "scrotum",
  "semen",
  "sex",
  "sexo",
  "sexo oral",
  "sh!+",
  "sh!t",
  "sh1t",
  "shag",
  "shagger",
  "shaggin",
  "shagging",
  "shemale",
  "shi+",
  "shit",
  "shitdick",
  "shite",
  "shited",
  "shitey",
  "shitfuck",
  "shitfull",
  "shithead",
  "shiting",
  "shitings",
  "shits",
  "shitted",
  "shitter",
  "shitters",
  "shitting",
  "shittings",
  "shitty",
  "skank",
  "slut",
  "sluts",
  "smegma",
  "smut",
  "snatch",
  "son-of-a-bitch",
  "soplagaitas",
  "soplapollas",
  "spac",
  "spunk",
  "t1tt1e5",
  "t1tties",
  "teets",
  "teez",
  "testical",
  "testicle",
  "tetas grandes",
  "tia buena",
  "tit",
  "titfuck",
  "tits",
  "titt",
  "tittie5",
  "tittiefucker",
  "titties",
  "tittyfuck",
  "tittywank",
  "titwank",
  "torneira",
  "tosser",
  "transar",
  "travesti",
  "trio",
  "turd",
  "tw4t",
  "twat",
  "twathead",
  "twatty",
  "twunt",
  "twunter",
  "v14gra",
  "v1gra",
  "vadia",
  "vagina",
  "vai tomar no cu",
  "vai-te foder",
  "veado",
  "verga",
  "vete a la mierda",
  "viagra",
  "vibrador",
  "vulva",
  "w00se",
  "wang",
  "wank",
  "wanker",
  "wanky",
  "whoar",
  "whore",
  "willies",
  "willy",
  "xana",
  "xochota",
  "xrated",
  "xxx"
];
  const ALLOWED_TERMS = new Set([
    "bissexual",
    "homosexual",
    "lesbica",
  ]);
  const LEET_REPLACEMENTS = {
    "0": "o",
    "1": "i",
    "3": "e",
    "4": "a",
    "5": "s",
    "7": "t",
    "8": "b",
    "9": "g",
    "@": "a",
    "$": "s",
    "!": "i",
    "|": "i",
  };

  function normalizeForFilter(value) {
    return String(value || "")
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[01345789@$!|]/g, (character) => LEET_REPLACEMENTS[character] || character);
  }

  function normalizeLiteral(value) {
    return String(value || "")
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase();
  }

  function compact(value) {
    return normalizeForFilter(value).replace(/[^a-z0-9]/g, "");
  }

  function compactLiteral(value) {
    return normalizeLiteral(value).replace(/[^a-z0-9]/g, "");
  }

  const exactWords = new Set(BAD_WORDS.map(normalizeForFilter).filter((word) => word && !ALLOWED_TERMS.has(word)));
  const compactWords = new Set(BAD_WORDS.map(compact).filter((word) => word && !ALLOWED_TERMS.has(word)));
  const digitWrappedWords = Array.from(compactWords).filter((word) => word.length >= 5);

  function hasDigitWrappedWord(compactValue, literalCompactValue) {
    return digitWrappedWords.some((word) => {
      if (compactValue.startsWith(word) && /^\d+$/.test(literalCompactValue.slice(word.length))) {
        return true;
      }
      if (compactValue.endsWith(word) && /^\d+$/.test(literalCompactValue.slice(0, -word.length))) {
        return true;
      }
      return false;
    });
  }

  function containsProfanity(value) {
    const normalized = normalizeForFilter(value);
    const tokens = normalized.split(/[^a-z0-9]+/).filter(Boolean);
    if (tokens.some((token) => exactWords.has(token) || compactWords.has(token))) {
      return true;
    }

    const compactValue = normalized.replace(/[^a-z0-9]/g, "");
    if (!compactValue) return false;
    if (exactWords.has(compactValue) || compactWords.has(compactValue)) return true;

    return hasDigitWrappedWord(compactValue, compactLiteral(value));
  }

  window.FLAPPY_FISH_NAME_FILTER = Object.freeze({ containsProfanity });
})();
